### ISSUE TITLE
Enable use of RStudio preview releases and installation of quarto

### ISSUE THREAD

**Issue by srvanderplas** [pachadotdev/r-packages-ubuntu#2]
Thanks for this script - I'm hoping it will make setting R up across multiple machines easier. 

It would be very convenient for those of us who use the preview release of RStudio if that were an option that we could enable in this script. 

I'd also love it if it were possible to keep Quarto updated using this same method. Is that something you'd consider?

Thanks again!

**Comment by pachadotdev** [comment]
hi @srvanderplas 
indeed, I can provide the unstable/daily version of rstudio and quarto

**Comment by pachadotdev** [comment]
@srvanderplas I added quarto to the main APT, I tested this

```
$ sudo apt install quarto
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  quarto
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 88.7 MB of archives.
After this operation, 313 MB of additional disk space will be used.
Get:1 https://apt.pacha.dev ./ quarto 1.3.340 [88.7 MB]
Fetched 88.7 MB in 4s (20.0 MB/s) 
Selecting previously unselected package quarto.
(Reading database ... 687508 files and directories currently installed.)
Preparing to unpack .../quarto_1.3.340_amd64.deb ...
Unpacking quarto (1.3.340) ...
Setting up quarto (1.3.340) ...
```

Regarding RStudio daily, I added a side APT (https://apt-daily.pacha.dev) and I updated the script accordingly, which shall ask you if you want to install the daily build, so the instructions are the same from the README

**Comment by srvanderplas** [comment]
Thanks!
