### ISSUE TITLE
bspm package error

### ISSUE THREAD

**Issue by sara-edu** [pachadotdev/r-packages-ubuntu#3]
`Error in loadNamespace(x) : there is no package called ‘bspm’`

After completing the installation, when I open the RStudio, it shows the above error. Also pls see attached image of an error.

Due to this error, I'm not able to install any packages.

![Screenshot from 2023-05-15 23-42-20](https://github.com/pachadotdev/r-packages-ubuntu/assets/128784078/281b3f04-77d4-4fa5-bc3c-b8429e805a5d)

**Comment by pachadotdev** [comment]
hi @sara-edu 
can you show me the system information? a simple `sessionInfo()` from R is ok

**Comment by pachadotdev** [comment]
@sara-edu I just tried on a new virtual machine, and it works here. In the meanwhile, you can run `sudo gedit /etc/R/Rprofile.site` and delete the final line (the one about bpsm). Send me your log and system information, please.

**Comment by sara-edu** [comment]
`bspm` error is gone after trying the steps for Ubuntu from this slide [https://enchufa2.github.io/bspm/slides/20210709-useR2021_talk.html#28](url).

Now no more `bspm` error. But a warning in the R console, pls see an attached SS.

![Screenshot from 2023-05-16 09-57-32](https://github.com/pachadotdev/r-packages-ubuntu/assets/128784078/c6165e79-db13-403e-8e56-15bb23a134b4)

**Comment by sara-edu** [comment]
> hi @sara-edu can you show me the system information? a simple `sessionInfo()` from R is ok

Yes, the session information is:

![Screenshot from 2023-05-16 10-41-52](https://github.com/pachadotdev/r-packages-ubuntu/assets/128784078/4dc5d54c-67af-4d54-9b95-cff805e12a1e)

**Comment by pachadotdev** [comment]
@sara-edu hi! good to know it worked, did you configure bpsm globally or for your user?

**Comment by pachadotdev** [comment]
@sara-edu also, slide 28 is exactly what my script does!

here are the steps
```


$ sudo add-apt-repository ppa:marutter/rrutter4.0   # R v4.0 and higher
$ sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+  # R packages
$ sudo apt-get update
$ sudo apt-get install r-cran-bspm python3-{dbus,gi,apt}
$ echo "bspm::enable()" | sudo tee -a /etc/R/Rprofile.site
```

**Comment by pachadotdev** [comment]
@sara-edu regarding warning, remove bpsm from `~/R`, and follow the exact steps from the warning (you have to run it in a console). Your screenshot reflects you are using a desktop setup, which is the use case I had in mind.

**Comment by sara-edu** [comment]
> @sara-edu hi! good to know it worked, did you configure bpsm globally or for your user?

I think I used bpsm globally.

**Comment by sara-edu** [comment]
> @sara-edu regarding warning, remove bpsm from `~/R`, and follow the exact steps from the warning (you have to run it in a console). Your screenshot reflects you are using a desktop setup, which is the use case I had in mind.

Inside the R folder, I can see a folder named as `bslib`. Should I move it to thrash?

**Comment by pachadotdev** [comment]
> 

@sara-edu no, that is another package
