### ISSUE TITLE
Package Installation is stuck

### ISSUE THREAD

**Issue by rishieco** [pachadotdev/r-packages-ubuntu#4]
Hello, thank you for the wonderful script. It seems to be the most useful solution to have a well functioning R environment in Linux.
I had tried the script on pop OS and it worked perfectly all right. However, on Ubuntu 22.04, the package installation remains stuck (please see the last line of the output pasted below). Can you please help resolve this and let me know if I should provide additional information. Thank you.

1] "install.packages(ggplot2)"
> install.packages("ggplot2")
Available system packages...
Hit https://dl.google.com/linux/chrome/deb stable InRelease                     
Hit http://security.ubuntu.com/ubuntu jammy-security InRelease                  
Get:1 https://zotero.retorque.re/file/apt-package-archive ./ InRelease [2153 B] 
Hit https://apt.pacha.dev ./ InRelease                                          
Get:2 https://apt-daily.pacha.dev ./ InRelease [1662 B]                         
Hit https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit https://ppa.launchpadcontent.net/marutter/rrutter4.0/ubuntu jammy InRelease 
Hit http://in.archive.ubuntu.com/ubuntu jammy InRelease                         
Hit http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease                 
Get:3 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]    
Fetched 112 kB in 6s (632 B/s)                                                  

  There is a binary version available but the source version is later:
        binary source
isoband  0.2.6  0.2.7

Do you prefer later versions from sources? (Yes/no/cancel) no
Install system packages...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
  ading state information... 0%

**Comment by pachadotdev** [comment]
hi @rishieco 
is not stuck, you should ideally select "no" and avoid compiling from sources
otherwise, select "yes" and compile the most recent version, but make sure to go to prepare some coffee

**Comment by pachadotdev** [comment]
also @rishieco, can you send me a screenshot
sometimes pressing ENTER just works from VSCode

**Comment by rishieco** [comment]
Hi, thank you. You are right; selecting "no" and installing "binary packages" seems to work but its is taking a long time and nothing seems to be happening after this message-  "ading state information... 0%" 

Later I used the "yes" to install the same packages and it worked well for "tidyverse", "secr" etc- no errors or problems so far.
I am very happy with that and your script seemed to have taken care of dependency issues which I have always faced in ubuntu with r so far. So thank you for that!

I will send you a screen shot of the issue later.

**Comment by pachadotdev** [comment]
Well, I did nothing but happy it worked.

**Comment by pachadotdev** [comment]
@rishieco hi! which Pop version are you using?

**Comment by rishieco** [comment]
Hi its is 22.04 LTS (NVIDIA) on a thinkpad T480

**Comment by pachadotdev** [comment]
> 

Thanks! amazing laptop, kinda heavy for me but a great one. I use a Thinkpad x1 carbon here, amazing battery life and very light (1.8 lbs)
