### ISSUE TITLE
Running into an error while updating

### ISSUE THREAD

**Issue by rishieco** [pachadotdev/r-packages-ubuntu#5]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base-dev is already the newest version (4.3.1-2.2204.0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Do you want to install Git?
1) Yes
2) No
#? 1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.9).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Is it ok to add apt.pacha.dev as a source for RStudio and/or Quarto?
bash: -c: line 80: syntax error near unexpected token `&&'
bash: -c: line 80: ` && echo "deb https://apt.pacha.dev ./" | tee /etc/apt/sources.list.d/pacha.list > /dev/null && apt update; break;;'

**Comment by pachadotdev** [comment]
Thanks for reporting. I'll test on a virtual machine to isolate any influence and fix it accordingly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Rishi Kumar Sharma ***@***.***>
Sent: Monday, July 17, 2023 6:42:05 PM
To: pachadotdev/r-packages-ubuntu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pachadotdev/r-packages-ubuntu] Running into an error while updating (Issue #5)


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base-dev is already the newest version (4.3.1-2.2204.0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Do you want to install Git?

  1.  Yes
  2.  No
#? 1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.9).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Is it ok to add apt.pacha.dev as a source for RStudio and/or Quarto?
bash: -c: line 80: syntax error near unexpected token &&' bash: -c: line 80: && echo "deb https://apt.pacha.dev ./" | tee /etc/apt/sources.list.d/pacha.list > /dev/null && apt update; break;;'

**Comment by pachadotdev** [comment]
hi @rishieco 
it was an accidental line break
it's fixed now
